// netlify/functions/addDomain.js
const Airtable = require("airtable");
const { requireUser } = require("./_lib/auth");

exports.handler = async (event) => {
  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  };

  if (event.httpMethod === "OPTIONS") return { statusCode: 200, headers, body: "" };
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, headers, body: JSON.stringify({ error: "Method not allowed" }) };
  }

  try {
    const user = await requireUser(event);
    const { domain, subdomain, type, smtp } = JSON.parse(event.body || "{}");

    if (!domain) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: "Domain required" }) };
    }

    const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY }).base(process.env.AIRTABLE_BASE_ID);

    const fields = {
      userId: user.uid,
      domain,
      type: type || "gmail",
      status: "pending",
      spfStatus: "pending",
      dkimStatus: "pending",
      dmarcStatus: "pending",
      mxStatus: "pending",
      accountsUsing: 0,
    };

    // Add subdomain if provided
    if (subdomain) {
      fields.subdomain = subdomain;
    }

    // Add SMTP config if provided
    if (type === "smtp" && smtp) {
      fields.smtpHost = smtp.host;
      fields.smtpPort = smtp.port;
      fields.smtpUsername = smtp.username;
      fields.smtpPassword = smtp.password; // TODO: Encrypt this
      fields.smtpConfigured = true;
    }

    // Generate DNS records
    const fullDomain = subdomain ? `${subdomain}.${domain}` : domain;
    
    fields.spfRecord = `v=spf1 include:_spf.google.com ~all`; // Example SPF
    fields.dmarcRecord = `v=DMARC1; p=none; rua=mailto:dmarc@${domain}`;
    // DKIM would be generated by email provider
    fields.mxRecord = type === "gmail" 
      ? "1 ASPMX.L.GOOGLE.COM" 
      : smtp?.host || "";

    const record = await base("Domains").create(fields);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        domain: {
          id: record.id,
          ...record.fields,
        },
      }),
    };
  } catch (error) {
    console.error("addDomain error:", error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: "Failed to add domain", details: error.message }),
    };
  }
};